name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      name: checkout nosqlbench

    - uses: actions/setup-java@v3
      name: setup java
      with:
        java-version: '17'
        java-package: jdk
        architecture: x64
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: mvn package
      run: mvn package

    - name: mvn verify
      run: mvn verify

    - name: Capture
      run: tar -cvf jbanks_files.tar [a-zA-Z]**/logs/*

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: jbanks_files.tar
