name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: checkout nosqlbench
      - uses: actions/setup-java@v3
        name: setup java
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: mvn package
        run: mvn package

      - name: export docs
        run: nb5/target/nb5 export-docs

      - name: archive docs
        uses: actions/upload-artifact@v3
        with:
          name: exported-docs
          path: exported_docs.zip

#      - name: mvn verify
#        run: mvn verify

#      - name: Archive Test Results
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-results
#          path: |
#            [a-zA-Z]**/logs/*


  docs:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: set git username
        run: git config --global user.email "${{ secrets.NBDROID_EMAIL }}"

      - name: set git email
        run: git config --global user.name "${{ secrets.NBDROID_NAME }}"

      - name: download exported-docs
        uses: actions/download-artifact@v3
        with:
          name: exported-docs

      - name: unzip docs
        run: unzip exported_docs.zip

      - run: ls -la

      #      - name: download docs
      #        uses: actions/download-artifact@v1
      #        with:
      #          name: guidebook
      #          path: guidebook

      - name: clone nosqlbench-build-docs
        env:
          NBDROID_NAME: ${{ secrets.NBDROID_NAME }}
          NBDROID_TOKEN: ${{ secrets.NBDROID_TOKEN }}
        run: |
          git clone https://${{secrets.NBDROID_NAME}}:${{secrets.NBDROID_TOKEN}}@github.com/nosqlbench/nosqlbench-build-docs.git nosqlbench-build-docs
          cd nosqlbench-build-docs
          echo "files listing"
          find .
          git remote set-url origin https://${{secrets.NBDROID_NAME}}:${{secrets.NBDROID_TOKEN}}@github.com/nosqlbench/nosqlbench-build-docs.git
          git remote -v

      #      Disabling this because it will be replaced soon.
      - name: push changes
        env:
          NBDROID_NAME: ${{ secrets.NBDROID_NAME }}
          NBDROID_TOKEN: ${{ secrets.NBDROID_TOKEN }}
        run: |
          rsync -av --delete drivers/ nosqlbench-build-docs/site/docs/drivers
          echo "previewdocs.nosqlbench.io" > nosqlbench-build-docs/site/content/docs/drivers/CNAME
          git add drivers
          git add -u
          rsync -av --delete bindings/ nosqlbench-build-docs/site/docs/bindings
          echo "previewdocs.nosqlbench.io" > nosqlbench-build-docs/site/content/docs/bindings/CNAME
          git add bindings
          git add -u
          CHANGES=$(git status --porcelain 2>/dev/null| wc -l)
          echo "found $CHANGES to push for doc updates"
          if (( $CHANGES > 0 ))
          then
            git commit -m"docs update for $GITHUB_REF"
            git push
          fi
